In [3]:
# importing libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


# loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()


# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
df_filled = df

In [9]:
df_filled.loc[:,['salary_year_avg','salary_hour_avg']]

        salary_year_avg  salary_hour_avg
0                   NaN              NaN
1                   NaN              NaN
2                   NaN              NaN
3                   NaN              NaN
4                   NaN              NaN
...                 ...              ...
785736              NaN              NaN
785737              NaN              NaN
785738              NaN              NaN
785739              NaN              NaN
785740              NaN              NaN

[785741 rows x 2 columns]

In [10]:
median_year_salary = df_filled['salary_year_avg'].median()

In [12]:
median_hour_salary = df_filled['salary_hour_avg'].median()

In [17]:
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_year_salary)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_hour_salary)

In [18]:
df_filled.loc[:,"salary_year_avg":"salary_hour_avg"]

        salary_year_avg  salary_hour_avg
0              115000.0            45.98
1              115000.0            45.98
2              115000.0            45.98
3              115000.0            45.98
4              115000.0            45.98
...                 ...              ...
785736         115000.0            45.98
785737         115000.0            45.98
785738         115000.0            45.98
785739         115000.0            45.98
785740         115000.0            45.98

[785741 rows x 2 columns]

In [22]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print("df_filled :", df_filled.shape[0])
print("df_unique :", df_unique.shape[0])
print("Dropped rows :", df_filled.shape[0]-df_unique.shape[0] )

df_filled : 785741
df_unique : 785640
Dropped rows : 101

In [30]:
df_unique = df_unique.drop_duplicates(subset = ['job_title','company_name'])

print("df_filled :", df_filled.shape[0])
print("df_unique :", df_unique.shape[0])
print("Dropped rows :", df_filled.shape[0]-df_unique.shape[0] )

df_filled : 785741
df_unique : 508042
Dropped rows : 277699

In [33]:
print(df_filled.shape)
print(df_unique.shape)

(785741, 17)
(508042, 17)